### ISSUE TITLE
keyple-plugin/remotese plugin constructor design

### ISSUE THREAD

**Issue by pterr** [eclipse/keyple-java#130]
org.eclipse.keyple.plugin.remotese.pluginse.RemoteSePluginFactory should be public.
RemoteSePluginFactory shouldn't be operated inside org.eclipse.keyple.plugin.remotese.pluginse.MasterAPI 
As for any plugin setting, RemoteSePluginFactory should be registered to SeProxyService by the ticketing application.

The Remote SE Plugin is more complex to initialize than the other plugins.

- maybe the MasterAPI constructors could take a RemoteSePlugin or a RemoteSePoolPlugin
- if necessary, a specific public initialization method could be added in RemoteSePlugin

**Comment by odelcroi** [comment]
For now, the user only have to instantiate the MasterAPI, then it will register the plugin to the SeProxy 
For consistency with other plugin initialisation, we could ask the user to register the RemoteSePlugin and then pass it to the MasterAPI.
