### ISSUE TITLE
Making asynchronous processing possible for reader events

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#147]
The reader events would become:
- SE_INSERTED
- SE_REMOVAL_PENDING
- SE_WAIT_FOR_INSERTION

A new method to add in the ObservableReader interface:
void terminate(boolean waitForRemoval)

The application will have to call this method at the end of the SE processing. A timeout mechanism will be implemented.

**Comment by odelcroi** [comment]
#162
