### ISSUE TITLE
Update of the Android NFC plugin to implement the same state machine as in AbstractThreadedLocalReader

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#150]

**Comment by pterr** [comment]
**About org.eclipse.keyple.plugin.android.nfc.AndroidNfcReader & AndroidNfcReaderImpl**
The public interface AndroidNfcReader may not extend NfcAdapter.ReaderCallback & NfcAdapter.OnTagRemovedListener
Instead the package protected class AndroidNfcReaderImpl may extend NfcAdapter.ReaderCallback
AndroidNfcPluginImpl may extend NfcAdapter.OnTagRemovedListener in the future for Android > 7, write a TODO

method onTagDiscovered(Tag tag), for case WAIT_FOR_START_DETECTION: => ignore notification
method onTagRemoved(), for case WAIT_FOR_START_DETECTION: => ignore notification

method startRemovalSequence(),

- for cases WAIT_FOR_SE_INSERTION, WAIT_FOR_SE_REMOVAL & WAIT_FOR_START_DETECTION: =S state error

- for case WAIT_FOR_SE_PROCESSING: => repeat with delay calls to AbstractObservableLocalReader isSePresentPing()

overwrite startSeDetection(ObservableReader.PollingMode pollingMode)

**About org.eclipse.keyple.plugin.AbstractThreadedObservableLocalReader & AbstractObservableLocalReader**
Move AbstractThreadedObservableLocalReader.isSePresentPing() in AbstractObservableLocalReader
	remove Thread.sleep(30); from isSePresentPing()

**Comment by odelcroi** [comment]
#162
