### ISSUE TITLE
pcsc : jvm crash with a pcsc example on MacOs

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#153]
OS : macOs 10.12.6

Random crash while running Demo_ObservableReaderNotification_Pcsc on MacOs Sierra 10.12.6

see attached dump 

A fatal error has been detected by the Java Runtime Environment:
SIGILL (0x4) at pc=0x00007fff905587cd, pid=6190, tid=22531

JRE version: Java(TM) SE Runtime Environment (8.0_40-b27) (build 1.8.0_40-b27)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C  [libdispatch.dylib+0x17cd]  _os_object_release+0x31

[hs_err_pid6190.log.txt](https://github.com/eclipse/keyple-java/files/3728088/hs_err_pid6190.log.txt)

**Comment by pterr** [comment]
Investigate if the issue happens only on MacOS. Check if this issue is due to a defect of the Keyple Core or PC/SC plugin, or if it’s linked to a limitation of the PCSClite implementation for MacOS.

**Comment by odelcroi** [comment]
Need to be reproduced with 0.8

**Comment by odelcroi** [comment]
Reproduced in 0.8, investigating..

**Comment by odelcroi** [comment]
The method used for detecting card has been switched to terminal#isCardPresent() from smartcard.io which gives more stability, however with multiple (3 and more) readers connected, the system is not 100% stable.
