### ISSUE TITLE
filename too long

### ISSUE THREAD

**Issue by angelsephirot** [eclipse/keyple-java#154]
when trying to pull on windows , there is path which are above the authorized length:
15:48	Clone failed
			unable to create file java/example/calypso/pc/UseCase_Calypso2_DefaultSelectionNotification/src/main/java/org/eclipse/keyple/example/calypso/pc/UseCase_Calypso2_DefaultSelectionNotification/UseCase_Calypso2_DefaultSelectionNotification_Pcsc.java: Filename too long
			unable to create file java/example/calypso/pc/UseCase_Calypso2_DefaultSelectionNotification/src/main/java/org/eclipse/keyple/example/calypso/pc/UseCase_Calypso2_DefaultSelectionNotification/UseCase_Calypso2_DefaultSelectionNotification_Stub.java: Filename too long
			unable to create file java/example/generic/pc/UseCase_Generic2_DefaultSelectionNotification/src/main/java/org/eclipse/keyple/example/generic/pc/UseCase_Generic2_DefaultSelectionNotification/UseCase_Generic2_DefaultSelectionNotification_Pcsc.java: Filename too long
			unable to create file java/example/generic/pc/UseCase_Generic4_SequentialMultiSelection/src/main/java/org/eclipse/keyple/example/generic/pc/UseCase_Generic4_SequentialMultiSelection/UseCase_Gen... (show balloon)

**Comment by angelsephirot** [comment]
issue can be solve with :
`git config --system core.longpaths true`

Will be better to shorten filename and path.

**Comment by jeanpierrefortune** [comment]
The reorganization of the examples folder is still in progress. We will take into account this remark concerning the length of paths.
Thank you.

**Comment by pterr** [comment]
OK, for the next commit of 'example' we will reduce all long paths of examples by 46 characters.

**Comment by curious-jeremy** [comment]
:+1:
