### ISSUE TITLE
remotese : create VirtualObservableReader

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#165]

**Comment by pterr** [comment]
Maybe, define a VirtualObservableReader (implements ObservableReader, & extends VirtualReader) => the notifySeProcessed() method may be implemented by VirtualObservableReader.

**Comment by odelcroi** [comment]
make UT for 0.8 : 
VirtualReader is Observable, then notifySeProcessed is available.
What happen if the nativeReader is not Observable?

**Comment by pterr** [comment]
VirtualReader may no more be Observable.

- if a nativeReader isn't ObservableReader, then the Remote SE plugin should create a simple VirtualReader.
- if a nativeReader is ObservableReader, then the Remote SE plugin should create a simple VirtualObservableReader.

Only VirtualObservableReader should support notifySeProcessed, not VirtualReader.

**Comment by odelcroi** [comment]
Ok
