### ISSUE TITLE
remotese : VirtualReader should be observable or not

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#172]
Depending if the NativeReader is Observable or not

Study what are the use cases

**Comment by pterr** [comment]
Response already commented in https://github.com/eclipse/keyple-java/issues/165

- VirtualReader should implement SeReader, not ObservableReader.

- VirtualObservable should implement ObservableReader.

- If a NativeReader is ObservableReader, then connected with a Remote SE => a VirtualObservableReader should be created.

- If a NativeReader isn't ObservableReader, then connected with a Remote SE => a VirtualReader should be created.
