### ISSUE TITLE
For ObservablePlugin, set a PluginObserver to be notified of reader changes, only for readers with names matching a regex

### ISSUE THREAD

**Issue by pterr** [eclipse/keyple-java#195]
In org.eclipse.keyple.core.seproxy.event.ObservablePlugin the current method

- `void addObserver(PluginObserver observer);`

allows to set an Observer for all the readers of a plugin.

In addition, the definition of a new method 

- `void addObserver(PluginObserver observer, String readerNameRegex);`

will allow an Observer to **be notified for changes on readers only having a name matching a specific regular expression**.

For example, useful for some Calypso use cases, in order to defined from the same plugin an observer of SAM readers, and separately an observer of PO readers.

Linked with the issue eclipse/keyple-service-java-lib#47

**Comment by odelcroi** [comment]
I think this need is specific to PCSC, would it be cleaner to implement it only in the PCSC plugin?
