### ISSUE TITLE
NullpointerException On RemoteMethodTxEngine

### ISSUE THREAD

**Issue by BrandaoFrancois** [eclipse/keyple-java#295]
On onDTO method of RemoteMethodTxEngine, if remoteMethodTx is null, we have a Nullpointer Exception. Because, their is a test which only log but continu treatment after.

https://github.com/eclipse/keyple-java/blob/5fe61ed8c663119ee122e69fd9bf58c6825787da/java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/RemoteMethodTxEngine.java#L87

**Comment by odelcroi** [comment]
https://keyple.atlassian.net/browse/KEYP-190
fixed
