### ISSUE TITLE
RemoteSePoolPlugin collections of SeReader not thread-safe

### ISSUE THREAD

**Issue by hicham-elbizy** [eclipse/keyple-java#298]
In class RemoteSePoolPlugin, the collection of  seSeader is shared between multiple threads:  if the current thread executes the iteration and the second thread is modifying the collection of readers (adding or removing virtualReader), while the current thread still iterating over elements, the exception ConcurrentModificationException  to be thrown and fails immediately

**Comment by odelcroi** [comment]
https://keyple.atlassian.net/browse/KEYP-195

**Comment by odelcroi** [comment]
fixed
