### ISSUE TITLE
An alive background Thread prevent Main from stopping

### ISSUE THREAD

**Issue by alexandre-jannotta** [eclipse/keyple-java#342]
Here is a simple main :

https://gist.github.com/alexandre-jannotta/1d4cb6abc82397f0132bb048012f09f6

A background Thread "pool-1-thread-1" generated by Keyple prevent process exit.

Could you please fix this ?

**Comment by jeanpierrefortune** [comment]
Hello Alexandre,

First of all, thank you for contributing to the improvement of Keyple!

Concerning the background thread you're talking about, there are indeed threads created by Keyple notably for monitoring plugins (inserting readers) and readers (presenting secure elements).

The logic of Keyple is to start these threads as needed when observers are added and these threads are stopped when observers are removed.

Moreover, the principle of using Keyple in "observed" (vs. "explicit") mode is to start observing the readers and then to keep the application in an endless wait (a bit like the Calypso/Demo_CalypsoClassic_Pcsc example illustrates briefly).

In your example, the "test" method called "main" does not implement this waiting and does not remove the observer added at startup.
It is therefore logical that a "ghost" thread persists at exit.

I hope I have answered the question, but if I have not, I remain available to provide further information on the operation and implementation of Keyple.

This being said, we are preparing the release of a new version 0.9 which revisits in depth some aspects of the Keyple API, in particular facilitating the realization of applications.

You can already use a snapshot version (develop branch) or wait a week or two.

**Comment by alexandre-jannotta** [comment]
Partially,

In fact, if Keyple create a background Thread it should be marked as "daemon".
For example
```java
private final ExecutorService executorService = Executors.newSingleThreadExecutor(runnable -> {
    final Thread thread = new Thread(runnable, "keyple");
    thread.setDaemon(true);
    return thread;
});
```
Could replace https://github.com/eclipse/keyple-java/blob/eadf16071f8b59bb481c20456437f53950050d5b/java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscReaderImpl.java#L65

This could permit to an application to exit without having to shutdown the executor.

**Comment by jeanpierrefortune** [comment]
Hello Alexandre,

Thanks for your interest in improving Keyple!

We have taken note of this point regarding thread management. As we will review this part of Keyple which also include other areas of optimization in the coming weeks, we will take care to better manage thread properties!
