### ISSUE TITLE
RATIFICATION

### ISSUE THREAD

**Issue by CIBEST25** [eclipse/keyple-java#502]
there is a bug in Keyple 1.0.0, concerning the session closing which sends a ratification command to the card even if
the close session command specifies that the ratification is automatic (80H)

The fix is simple : 
-->Change in PoTransaction.java L454: CLOSE_RATIFIED to CLOSE_NOT_RATIFIED

**Comment by andrei-cristea** [comment]
Hello,

As indicated on the repository homepage, **Keyple 1.0 is no longer maintained**.

Many corrections and improvements have been made in version 2.0

Here is the link to the project website: https://keyple.org/
