### ISSUE TITLE
Extract and keep the DF name during the selection process

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#51]
The selection process takes into account the currently selected SE. However, the data kept for this purpose are the latest AID which may be a subset of the full DF name.
Change this option to keep the full DF name extracted from the FCI data.
This requires early analysis of FCI data (as part of the selection process).

**Comment by pterr** [comment]
No more need of cache for the selected DF Name, in the new SE Proxy, a Selector is present only a SE Selection has to be processed. When a SE Selector is transmitted, a SE Selection is operated whatever the previous selected DF. Verified in https://github.com/eclipse/keyple-java/pull/225
