### ISSUE TITLE
Null pointer exception when making an explicit selection on an already selected SE

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#73]
Can be reproduced by duplicating the explicit selection call.

First level analysis: when the channel is already open, the selection process is shortened and the return selection status is null, resulting in a null active selection.

**Comment by jeanpierrefortune** [comment]
Not reproduced for now

**Comment by pterr** [comment]
Verified in https://github.com/eclipse/keyple-java/pull/225
