### ISSUE TITLE
keyple-core : unecessary exception in getReaders()

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#74]
Study if we need the KeypleReaderException in plugin#getReaders()

**Comment by odelcroi** [comment]
This method is widely used, the exception defined does not make a lot of sense

**Comment by odelcroi** [comment]
This exception is needed to notify the fact that the readers list is null, generally resulting in an error of initialization of the readers list at the instantiation of the plugin.

**Comment by pterr** [comment]
At the end of the registering of a plugin on SeProxyService, we could maybe check if the reader list is “null”.

- If it’s the case, we could consider that the registering of the plugin has failed, and then issues an Exception.
 
When registered a ReaderPlugin could have a list of SeReader: empty or with some items. But never null.

- So `ReaderPlugin .getReaders()` doesn’t necessary need an exception.

- But `SeProxyService registerPlugin(AbstractPluginFactory pluginFactory)` as it is currently defined, has to throw an exception.

**Comment by odelcroi** [comment]
Playing with null is discouraged, so it will be better to stick with exceptions. 

The proposed solution uses a KeypleRuntimeException in the constructor of the plugin
