### ISSUE TITLE
Remotese : make keypleDto pretty printing

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#92]
"bytes": [] are printed vertically in console -> make them inline

**Comment by LudovicTeixeiraCosta** [comment]
Please display data in hexadecimal format

**Comment by jeanpierrefortune** [comment]
https://gist.github.com/craigpatten/9125143 could help.

**Comment by odelcroi** [comment]
inline Json could help also to make logs more lisible

**Comment by odelcroi** [comment]
merge #93
